### ISSUE TITLE
KeyError: b'\x10'

### ISSUE THREAD

**Issue by egorsmkv** [lang-uk/ukrainian-word-stress#3]
I have been stressing my text and got this exception:

```
The word `представляє` is in dictionary, but lacks accents
The word `Адміністрації` is in dictionary, but lacks accents
The word `кореспондент` is in dictionary, but lacks accents
The word `адміністрації` is in dictionary, but lacks accents
The word `обґрунтуванні` is in dictionary, but lacks accents
The word `працівників` is in dictionary, but lacks accents
The word `працівників` is in dictionary, but lacks accents
The word `спостерігається` is in dictionary, but lacks accents
The word `місцезнаходження` is in dictionary, but lacks accents
Traceback (most recent call last):
  File "do_stress.py", line 10, in <module>
    p = stressify(l)
  File "/home/yehor/ext-disk/stress-ukrainian/ukrainian-word-stress/ukrainian_word_stress/stressify_.py", line 76, in __call__
    accents = find_accent_positions(self.dict, token.to_dict()[0], self.on_ambiguity)
  File "/home/yehor/ext-disk/stress-ukrainian/ukrainian-word-stress/ukrainian_word_stress/stressify_.py", line 111, in find_accent_positions
    accents_by_tags = _parse_dictionary_value(values[0])
  File "/home/yehor/ext-disk/stress-ukrainian/ukrainian-word-stress/ukrainian_word_stress/stressify_.py", line 191, in _parse_dictionary_value
    tags = decompress_tags(tags)
  File "/home/yehor/ext-disk/stress-ukrainian/ukrainian-word-stress/ukrainian_word_stress/tags.py", line 70, in decompress_tags
    return [TAG_BY_BYTE[bytes([b])] for b in tags_bytes]
  File "/home/yehor/ext-disk/stress-ukrainian/ukrainian-word-stress/ukrainian_word_stress/tags.py", line 70, in <listcomp>
    return [TAG_BY_BYTE[bytes([b])] for b in tags_bytes]
KeyError: b'\x10'
```

**Comment by Theodotus1243** [comment]
The same thing but a bit different 

```
Traceback (most recent call last):
  File "create_manifest.py", line 33, in <module>
    stressed_texts = stress(texts)
  File "create_manifest.py", line 15, in stress
    text_skip = stressify_skip(text)
  File "/home/bohdan/.local/lib/python3.8/site-packages/ukrainian_word_stress/stressify_.py", line 75, in __call__
    accents = find_accent_positions(self.dict, token.to_dict()[0], self.on_ambiguity)
  File "/home/bohdan/.local/lib/python3.8/site-packages/ukrainian_word_stress/stressify_.py", line 110, in find_accent_positions
    accents_by_tags = _parse_dictionary_value(values[0])
  File "/home/bohdan/.local/lib/python3.8/site-packages/ukrainian_word_stress/stressify_.py", line 190, in _parse_dictionary_value
    tags = decompress_tags(tags)
  File "/home/bohdan/.local/lib/python3.8/site-packages/ukrainian_word_stress/tags.py", line 70, in decompress_tags
    return [TAG_BY_BYTE[bytes([b])] for b in tags_bytes]
  File "/home/bohdan/.local/lib/python3.8/site-packages/ukrainian_word_stress/tags.py", line 70, in <listcomp>
    return [TAG_BY_BYTE[bytes([b])] for b in tags_bytes]
KeyError: b'\x0b'
```

**Comment by osyvokon** [comment]
This has been fixed. Please upgrade to the latest version and report again if it doesn't help (although I did stress testing on 40k words and it seems to work fine):

```bash
pip install --upgrade ukrainian-word-stress
```
