### ISSUE TITLE
Does not work with stanza 1.7.0

### ISSUE THREAD

**Issue by egorsmkv** [lang-uk/ukrainian-word-stress#4]
It gives the following error:

```
Traceback (most recent call last):
  File "/home/yehor/ext-ml-disk/tts/pflow-tts/pflowtts_pytorch/synthesis_example.py", line 23, in <module>
    stressify = Stressifier(stress_symbol=StressSymbol.CombiningAcuteAccent)
  File "/home/yehor/Tools/anaconda3/envs/pflowtts/lib/python3.10/site-packages/ukrainian_word_stress/stressify_.py", line 61, in __init__
    self.nlp = stanza.Pipeline(
  File "/home/yehor/Tools/anaconda3/envs/pflowtts/lib/python3.10/site-packages/stanza/pipeline/core.py", line 237, in __init__
    self.load_list = maintain_processor_list(resources, lang, package, processors, maybe_add_mwt=(not kwargs.get("tokenize_pretokenized")))
  File "/home/yehor/Tools/anaconda3/envs/pflowtts/lib/python3.10/site-packages/stanza/resources/common.py", line 225, in maintain_processor_list
    elif value in resources[lang][PACKAGES] and key in resources[lang][PACKAGES][value]:
KeyError: 'packages'
```

**Comment by egorsmkv** [comment]
Can confirm that it works with `stanza==1.5.1`

**Comment by osyvokon** [comment]
Unfortunately, I can't reproduce it. Tried to run in several environments, including a clean docker container.

In any case, I've just bumped dependencies versions. Stanza is at 1.7.0 right now. Please update to the most recent versions and let me know if it doesn't solve the issue:

```bash
pip install --upgrade ukrainian-word-stress
```
